# fly.toml app configuration file generated for ecommerceapp2-patient-dream-7581 on 2024-10-03T00:21:30+05:30
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'ecommerceapp2-patient-dream-7581'
primary_region = 'sin'

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
